spring:
  application:
    name: usersmanager
  datasource:
    url: jdbc:h2:mem:UsersManager
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

validations:
  password:
    regex: ^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[$@#%&!]).{8,}$

encryption:
  password:
    token-key: C5nMGIdZu_dZ41x1NvwE6OA-mjA=
