spring:
  application:
    name: usersmanager
  datasource:
    url: jdbc:h2:mem:UsersManager
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        id:
          generator: org.hibernate.id.UUIDGenerator
  jackson:
    serialization:
      write_dates_as_timestamps: false

validations:
  password:
    regex: ^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[$@#%&!]).{8,}$

encryption:
  password:
    token-key: 2DDSb0EK218toJNzhcljb8UeHYPruDN0_a0pt1xnXRHuB3f9j3Y1NQ==

auth:
  token:
    duration: 5
