openapi: 3.0.0
info:
  version: 1.0
  title: Users Manager
paths:
  /user:
    post:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                phones:
                  type: array
                  items:
                    type: object
                    properties:
                      number:
                        type: string
                      citycode:
                        type: string
                      countrycode:
                        type: string

      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  created:
                    type: string
                  modified:
                    type: string
                  token:
                    type: string
                  isActive:
                    type: string